version: '2.4'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app:/root/app
    command: bash
    links:
      - slackapi:api
    environment:
      TZ: ${TZ:-Asia/Tokyo}


  slackapi:
    build:
      context: slackapi
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./slackapi:/root/slackapi
    command: flask run -h 0.0.0.0 -p 3030
    links:
      - mysql:db
      - redis:redis
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      DEFAULT_SLACK_TOKEN: ${DEFAULT_SLACK_TOKEN}
      TZ: ${TZ:-Asia/Tokyo}

  scheduler:
    build:
      context: slackapi
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./slackapi:/root/slackapi
    command: python3 job_scheduler.py
    links:
      - mysql:db
      - redis:redis
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      DEFAULT_SLACK_TOKEN: ${DEFAULT_SLACK_TOKEN}
      TZ: ${TZ:-Asia/Tokyo}

  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ENTRYPOINT_INITDB: ${MYSQL_ENTRYPOINT_INITDB}
      TZ: ${TZ:-Asia/Tokyo}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    volumes:
      - ./data/redis:/data
    