version: '2.4'

services:

  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/root/app
      - /root/batch/node_modules
    tty: true
    command: /bin/bash
    links:
      - mysql:db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      SLACK_TOKEN: ${SLACK_TOKEN}

  slackapi:
    build:
      context: slackapi
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./slackapi:/root/slackapi
    command: /bin/bash
    links:
      - mysql:db
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      SLACK_TOKEN: ${SLACK_TOKEN}

  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ENTRYPOINT_INITDB: ${MYSQL_ENTRYPOINT_INITDB}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
