"""CreateSlackChannel

Revision ID: 03d16ee7c547
Revises: 9e14c12889d6
Create Date: 2019-12-11 13:32:01.399577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d16ee7c547'
down_revision = '9e14c12889d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_channels',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Channel ID'),
    sa.Column('team_id', sa.String(length=64), nullable=True, comment='Workspace ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Channel Name'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Channel Create Datetime'),
    sa.Column('topic', sa.Text(), nullable=True, comment='Channel Topic'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='Channel Purpose'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_channels')
    # ### end Alembic commands ###
