"""create_tables

Revision ID: 18083b656fc0
Revises: 
Create Date: 2019-12-15 18:32:53.036743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18083b656fc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspaces',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Workspace ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Workspace Name'),
    sa.Column('domain', sa.String(length=64), nullable=False, comment='Workspace Domain'),
    sa.Column('email_domain', sa.String(length=64), nullable=True, comment='Workspace Domain'),
    sa.Column('image_34', sa.Text(), nullable=False, comment='Avatar Icon(34)'),
    sa.Column('image_44', sa.Text(), nullable=False, comment='Avatar Icon(44)'),
    sa.Column('image_68', sa.Text(), nullable=False, comment='Avatar Icon(68)'),
    sa.Column('image_88', sa.Text(), nullable=False, comment='Avatar Icon(88)'),
    sa.Column('image_102', sa.Text(), nullable=False, comment='Avatar Icon(102)'),
    sa.Column('image_132', sa.Text(), nullable=False, comment='Avatar Icon(132)'),
    sa.Column('api_token', sa.Text(), nullable=False, comment='API Token'),
    sa.Column('active_flag', sa.Text(), nullable=False, comment='Crawler Active Flag'),
    sa.Column('delete_flag', sa.Boolean(), nullable=False, comment='Delete flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack_channels',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Primary Key({team_id}/{channel_id})'),
    sa.Column('local_id', sa.String(length=64), nullable=True, comment='Channel ID'),
    sa.Column('team_id', sa.String(length=64), nullable=True, comment='Workspace ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Channel Name'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Channel Create Datetime'),
    sa.Column('topic', sa.Text(), nullable=True, comment='Channel Topic'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='Channel Purpose'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_channels_local_id'), 'slack_channels', ['local_id'], unique=False)
    op.create_table('slack_members',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Primary Key({team_id}/{user_id})'),
    sa.Column('user_id', sa.String(length=64), nullable=True, comment='Slack UserID'),
    sa.Column('team_id', sa.String(length=64), nullable=False, comment='Team ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='User Name'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Delete Flag'),
    sa.Column('color', sa.String(length=64), nullable=False, comment='Color'),
    sa.Column('real_name', sa.String(length=128), nullable=False, comment='Real Name'),
    sa.Column('tz', sa.String(length=64), nullable=True, comment='Timezone'),
    sa.Column('tz_offset', sa.Integer(), nullable=False, comment='Timezone Offset'),
    sa.Column('image_24', sa.Text(), nullable=False, comment='Avatar Icon(24)'),
    sa.Column('image_32', sa.Text(), nullable=False, comment='Avatar Icon(32)'),
    sa.Column('image_48', sa.Text(), nullable=False, comment='Avatar Icon(48)'),
    sa.Column('image_72', sa.Text(), nullable=False, comment='Avatar Icon(72)'),
    sa.Column('image_192', sa.Text(), nullable=False, comment='Avatar Icon(192)'),
    sa.Column('image_512', sa.Text(), nullable=False, comment='Avatar Icon(2512'),
    sa.Column('is_bot', sa.Boolean(), nullable=False, comment='Bot Flag'),
    sa.Column('is_owner', sa.Boolean(), nullable=False, comment='Owner Flag'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Admin Flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_members_user_id'), 'slack_members', ['user_id'], unique=False)
    op.create_table('slack_messages',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Message ID({workspace_id}/{channel_id}/{ts})'),
    sa.Column('channel_id', sa.String(length=64), nullable=True, comment='Channel ID'),
    sa.Column('user_id', sa.String(length=64), nullable=True, comment='User ID(Workspace)'),
    sa.Column('text', sa.Text(), nullable=False, comment='Text Body'),
    sa.Column('ts', sa.String(length=64), nullable=False, comment='Post Timestamp'),
    sa.Column('thread_ts', sa.String(length=64), nullable=True, comment='Thread Timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['slack_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['slack_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_messages_ts'), 'slack_messages', ['ts'], unique=False)
    op.create_table('slack_attachments',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Primary Key({message_id}/{attachment_id})'),
    sa.Column('message_id', sa.String(length=128), nullable=True, comment='Message ID'),
    sa.Column('attachment_id', sa.String(length=64), nullable=True, comment='Attachment id'),
    sa.Column('service_name', sa.String(length=64), nullable=True, comment='サービスの名前(サイト名と思う)'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='ページタイトルと思う'),
    sa.Column('text', sa.Text(), nullable=True, comment='ページの概要'),
    sa.Column('original_url', sa.Text(), nullable=True, comment='URL情報'),
    sa.Column('thumb_url', sa.Text(), nullable=True, comment='サムネイル画像'),
    sa.Column('service_icon', sa.Text(), nullable=True, comment='サイトのアイコンが像'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['slack_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_attachments_attachment_id'), 'slack_attachments', ['attachment_id'], unique=False)
    op.create_table('slack_files',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Primary Key({message_id}/{file_id})'),
    sa.Column('message_id', sa.String(length=128), nullable=True, comment='Message ID'),
    sa.Column('file_id', sa.String(length=64), nullable=False, comment='File_ID'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='ファイル名'),
    sa.Column('filetype', sa.String(length=64), nullable=True, comment='ファイル種別'),
    sa.Column('size', sa.Integer(), nullable=True, comment='ファイルサイズ(Byte??)'),
    sa.Column('permalink', sa.Text(), nullable=True, comment='ファイルリンク(パーマリンク)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['slack_messages.id'], ),
    sa.PrimaryKeyConstraint('id', 'file_id')
    )
    op.create_index(op.f('ix_slack_files_filetype'), 'slack_files', ['filetype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_files_filetype'), table_name='slack_files')
    op.drop_table('slack_files')
    op.drop_index(op.f('ix_slack_attachments_attachment_id'), table_name='slack_attachments')
    op.drop_table('slack_attachments')
    op.drop_index(op.f('ix_slack_messages_ts'), table_name='slack_messages')
    op.drop_table('slack_messages')
    op.drop_index(op.f('ix_slack_members_user_id'), table_name='slack_members')
    op.drop_table('slack_members')
    op.drop_index(op.f('ix_slack_channels_local_id'), table_name='slack_channels')
    op.drop_table('slack_channels')
    op.drop_table('slack_workspaces')
    # ### end Alembic commands ###
