"""add_flag_to_workspace

Revision ID: 4461a16d702d
Revises: 206ff21bb217
Create Date: 2019-12-15 00:56:51.765299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4461a16d702d'
down_revision = '206ff21bb217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_workspaces', sa.Column('active_flag', sa.Text(), nullable=False, comment='Crawler Active Flag'))
    op.add_column('slack_workspaces', sa.Column('delete_flag', sa.Boolean(), nullable=False, comment='Delete flag'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_workspaces', 'delete_flag')
    op.drop_column('slack_workspaces', 'active_flag')
    # ### end Alembic commands ###
