"""create_table

Revision ID: 4e8ca9710216
Revises: 
Create Date: 2019-12-12 00:08:41.306133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8ca9710216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspaces',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Workspace ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Workspace Name'),
    sa.Column('domain', sa.String(length=64), nullable=False, comment='Workspace Domain'),
    sa.Column('email_domain', sa.String(length=64), nullable=False, comment='Workspace Domain'),
    sa.Column('image_34', sa.Text(), nullable=False, comment='Avatar Icon(34)'),
    sa.Column('image_44', sa.Text(), nullable=False, comment='Avatar Icon(44)'),
    sa.Column('image_68', sa.Text(), nullable=False, comment='Avatar Icon(68)'),
    sa.Column('image_88', sa.Text(), nullable=False, comment='Avatar Icon(88)'),
    sa.Column('image_102', sa.Text(), nullable=False, comment='Avatar Icon(102)'),
    sa.Column('image_132', sa.Text(), nullable=False, comment='Avatar Icon(132)'),
    sa.Column('api_token', sa.Text(), nullable=False, comment='API Token'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack_channels',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Channel ID'),
    sa.Column('team_id', sa.String(length=64), nullable=True, comment='Workspace ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Channel Name'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Channel Create Datetime'),
    sa.Column('topic', sa.Text(), nullable=True, comment='Channel Topic'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='Channel Purpose'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack_members',
    sa.Column('id', sa.String(length=64), nullable=False, comment='User ID(Workspace)'),
    sa.Column('team_id', sa.String(length=64), nullable=False, comment='Team ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='User Name'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Delete Flag'),
    sa.Column('color', sa.String(length=64), nullable=False, comment='Color'),
    sa.Column('real_name', sa.String(length=128), nullable=False, comment='Real Name'),
    sa.Column('tz', sa.String(length=64), nullable=True, comment='Timezone'),
    sa.Column('tz_offset', sa.Integer(), nullable=False, comment='Timezone Offset'),
    sa.Column('image_24', sa.Text(), nullable=False, comment='Avatar Icon(24)'),
    sa.Column('image_32', sa.Text(), nullable=False, comment='Avatar Icon(32)'),
    sa.Column('image_48', sa.Text(), nullable=False, comment='Avatar Icon(48)'),
    sa.Column('image_72', sa.Text(), nullable=False, comment='Avatar Icon(72)'),
    sa.Column('image_192', sa.Text(), nullable=False, comment='Avatar Icon(192)'),
    sa.Column('image_512', sa.Text(), nullable=False, comment='Avatar Icon(512)'),
    sa.Column('is_bot', sa.Boolean(), nullable=False, comment='Bot Flag'),
    sa.Column('is_owner', sa.Boolean(), nullable=False, comment='Owner Flag'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Admin Flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['slack_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_members')
    op.drop_table('slack_channels')
    op.drop_table('slack_workspaces')
    # ### end Alembic commands ###
