"""createslackmember

Revision ID: 505ba4358574
Revises: 0e694bc8aa36
Create Date: 2019-12-11 13:03:28.576727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505ba4358574'
down_revision = '0e694bc8aa36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_members',
    sa.Column('id', sa.String(length=64), nullable=False, comment='User ID(Workspace)'),
    sa.Column('team_id', sa.String(length=64), nullable=False, comment='Team ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='User Name'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Delete Flag'),
    sa.Column('color', sa.String(length=64), nullable=False, comment='Color'),
    sa.Column('real_name', sa.String(length=128), nullable=False, comment='Real Name'),
    sa.Column('tz', sa.String(length=64), nullable=False, comment='Timezone'),
    sa.Column('tz_offset', sa.Integer(), nullable=False, comment='Timezone Offset'),
    sa.Column('image_24', sa.Text(), nullable=False, comment='Avatar Icon(24)'),
    sa.Column('image_32', sa.Text(), nullable=False, comment='Avatar Icon(32)'),
    sa.Column('image_48', sa.Text(), nullable=False, comment='Avatar Icon(48)'),
    sa.Column('image_72', sa.Text(), nullable=False, comment='Avatar Icon(72)'),
    sa.Column('image_192', sa.Text(), nullable=False, comment='Avatar Icon(192)'),
    sa.Column('image_512', sa.Text(), nullable=False, comment='Avatar Icon(2512'),
    sa.Column('is_bot', sa.Boolean(), nullable=False, comment='Bot Flag'),
    sa.Column('is_owner', sa.Boolean(), nullable=False, comment='Owner Flag'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Admin Flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_members_team_id'), 'slack_members', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_members_team_id'), table_name='slack_members')
    op.drop_table('slack_members')
    # ### end Alembic commands ###
