"""add_post_time_field_to_slack_messages

Revision ID: 7149489cbe63
Revises: c049d36c5f5d
Create Date: 2019-12-16 08:55:04.949286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7149489cbe63'
down_revision = 'c049d36c5f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_messages', sa.Column('post_time', sa.DateTime(), nullable=False, comment='Post Datetime'))
    op.create_index(op.f('ix_slack_messages_post_time'), 'slack_messages', ['post_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_messages_post_time'), table_name='slack_messages')
    op.drop_column('slack_messages', 'post_time')
    # ### end Alembic commands ###
