"""add_post_time_field_to_slack_messages

Revision ID: 7149489cbe63
Revises: c049d36c5f5d
Create Date: 2019-12-16 08:55:04.949286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7149489cbe63'
down_revision = 'c049d36c5f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('slack_messages', sa.Column('post_time', sa.DateTime(), nullable=False, comment='Post Datetime'))
    op.create_index(op.f('ix_slack_messages_post_time'), 'slack_messages', ['post_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_messages_post_time'), table_name='slack_messages')
    op.drop_column('slack_messages', 'post_time')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
