"""add_delete_flag_to_channels

Revision ID: 9c438f494168
Revises: 7149489cbe63
Create Date: 2019-12-16 09:27:40.237127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c438f494168'
down_revision = '7149489cbe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_channels', sa.Column('delete_flg', sa.Boolean(), nullable=False, comment='Delete Channel Flag'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_channels', 'delete_flg')
    # ### end Alembic commands ###
