"""chain_relation_workspace_to_member

Revision ID: 9e14c12889d6
Revises: 505ba4358574
Create Date: 2019-12-11 13:16:14.280720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e14c12889d6'
down_revision = '505ba4358574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slack_members_team_id', table_name='slack_members')
    op.create_foreign_key(None, 'slack_members', 'slack_workspaces', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slack_members', type_='foreignkey')
    op.create_index('ix_slack_members_team_id', 'slack_members', ['team_id'], unique=False)
    # ### end Alembic commands ###
