"""create_slack_message

Revision ID: e63dd1ac734d
Revises: 03d16ee7c547
Create Date: 2019-12-11 13:42:15.820518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63dd1ac734d'
down_revision = '03d16ee7c547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
